general:
    samples: config/samples.tsv 
    mutations: config/mutations.tsv

    # the pipeline starts with a few rules that automatically check that all dataset ids filled in the samples table
    # and tagged with IRODS_Status=OK are valid and visible by the user
    # you may skip this step by setting this to true buy may face failed jobs in case the fastq files cannot be retrieved
    automatic_irods_check:
        disable: false
        project_names:
            - TP53_Y220C
            - FRAGMENTOMICS

#Tools versions
tools_versions:
    fragmentomics: "0.1.0"


ref:
    # ensembl species name
    species: homo_sapiens
    # genome build
    build: hg19
    # fasta file
    fasta: /mnt/beegfs02/database/bioinfo/Index_DB/BWA/0.7.17/UCSC/hg19.fa


params:
  fragments:
    neg_offset: -300
    pos_offset: 300
    flag_keep: 0x03
    flag_remove: 0x900
