general:
    tmpdir: /mnt/beegfs/scratch/j_samaniego/tmp
    samples: config/samples.tsv 
    mutations: config/mutations.tsv

    # the pipeline starts with a few rules that automatically check that all dataset ids filled in the samples table
    # and tagged with IRODS_Status=OK are valid and visible by the user
    # you may skip this step by setting this to true buy may face failed jobs in case the fastq files cannot be retrieved
    automatic_irods_check:
        disable: true
        project_names:
            - FRAGMENTOMICS

ref:
    # ensembl species name
    species: homo_sapiens
    # genome build
    build: hg19
    # fasta file
    fasta: /mnt/beegfs/database/bioinfo/Index_DB/BWA/0.7.17/UCSC/hg19.fa
    # dict file
    dict: /mnt/beegfs/database/bioinfo/Index_DB/BWA/0.7.17/UCSC/hg19.dict


params:
  fragments:
    neg_offset: -1000
    pos_offset: 1000
  picard_flag:
    flag_keep: 0x03
    flag_remove: 0x900
  picard:
        MarkDuplicates:
            remove_duplicates: true

