package:
  name: r-fragmentomics
  version: 0.99.0

source:
  path: ..

build:
  number: 0

outputs:
  - name: r-fragmentomics
    build:
      script: "R CMD INSTALL --build ."
    requirements:
      host:
        - r-base >=4.4,<4.5
      run:
        - r-base >=4.4,<4.5
        - bioconductor-rsamtools >=2.4
        - bioconductor-genomicalignments
        - bioconductor-biocparallel
        - bioconductor-biostrings
        - bioconductor-genomeinfodb
        - bioconductor-genomicranges
        - bioconductor-iranges
        - bioconductor-s4vectors
        - r-bh
        - r-ggplot2
        - r-dplyr
        - r-tidyr
        - r-readr
        - r-stringr
        - r-purrr
        - r-tibble
        - r-magrittr
        - r-scales
        - r-rcolorbrewer
        - r-ggseqlogo
        - r-ggh4x
        - r-progressr
        - r-future
        - r-future.apply
    test:
      requires:
        - r-base >=4.4,<4.5
      commands:
        - $R -e "library('fRagmentomics'); packageVersion('fRagmentomics');"

  # --- Package with bcftools
  - name: r-fragmentomics-bcftools
    noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('r-fragmentomics', exact=True) }}
        - bcftools >=1.21
    test:
      requires:
        - r-base >=4.4,<4.5
      commands:
        - bcftools --version
        - $R -e "library('fRagmentomics'); packageVersion('fRagmentomics');"

about:
  home: "https://github.com/ElsaB-Lab/fRagmentomics"
  license: "GPL-3.0-or-later"
  license_family: GPL
  summary: "fRagmentomics is a standardized and user-friendly R package that integrates fragmentomic feature extraction with fragment-level mutation annotation across all classes of small variants, enabling efficient exploration of fragment-level patterns in cfDNA."
