# @created: 20 May 25
# @modified: 20 May 25
# @author: Yoann Pradat
#
# This pipeline runs an analysis of reads characteristics from cfDNA experiments starting from BAM files.

include: "rules/common.smk"

##### Target rules #####

def get_input_rule_all(w):
    inputs = []
    # +++++++++
    #### IRODS
    # +++++++++
    # BAM, BAI, PDF, XML
    inputs += expand('%s/data/bam/{sample}.bam' % R_FOLDER, sample=samples)
    inputs += expand('%s/data/bam/{sample}.bam.bai' % R_FOLDER, sample=samples)
    inputs += expand('%s/data/pdf/{sample}.pdf' % R_FOLDER, sample=samples)
    inputs += expand('%s/data/xml/{sample}.xml' % R_FOLDER, sample=samples)
    # +++++++++
    #### FRAGMENTOMICS
    # +++++++++
    inputs += expand('%s/fragmentomics/{sample}.tsv' % R_FOLDER, sample=samples)
    return inputs

rule all:
    input:
        get_input_rule_all

##### Modules #####

include: "rules/setup.smk"
include: "rules/irods.smk"
include: "rules/fragments.smk"

##### End messages #####

onsuccess:
    print("Workflow finished, no error")

onerror:
    print("An error occurred")
