name: Test & Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  covr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install deps
        run: |
          install.packages(c('remotes','covr'))
          remotes::install_deps(dependencies = TRUE)
      - name: Run tests & upload coverage
        run: |
          library(covr)
          cov <- covr::package_coverage(type = 'tests')
          covr::codecov(coverage = cov)
        shell: Rscript {0}
