name: Test & Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  covr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      # ----- Install all R / Bioconductor deps + covr ------------------------
      - name: Install deps
        run: |
          install.packages("remotes")
          install.packages("covr")
          install.packages("BiocManager")      # si tu as des dépendances Bioconductor
          BiocManager::install(ask = FALSE)    # core Bioconductor pkgs
          remotes::install_deps(".", dependencies = TRUE)
        shell: Rscript {0}

      # ----- Run tests and upload coverage -----------------------------------
      - name: Run tests & upload coverage
        run: |
          cov <- covr::package_coverage(type = "tests")
          covr::codecov(coverage = cov, branch = "main")
        shell: Rscript {0}
