name: Test & Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  covr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Check R version
        run: |
          echo "Vérification de la version de R via Rscript --version:"
          Rscript --version
          echo "Vérification de la version de R via R -e 'print(R.version.string)':"
          R -e "print(R.version.string)"
        shell: bash

      - name: Install package dependencies
        run: |
          install.packages(c("remotes", "BiocManager"), repos = "https://cloud.r-project.org", Ncpus = 2)
          options(repos = BiocManager::repositories())
          BiocManager::install(ask = FALSE, update = FALSE) # Or specify Bioc version
          # dependencies = TRUE ensures 'Suggests' (like covr) are installed
          remotes::install_deps(dependencies = TRUE, Ncpus = 2)

          # Verify covr installation
          if (!requireNamespace("covr", quietly = TRUE)) {
            stop("covr package (expected from Suggests) was not installed. Check logs.")
          }
          print("'covr' package is available.")
        shell: Rscript {0}

      - name: Run tests & upload coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          # Load covr package
          cov <- covr::package_coverage(type = "tests")
          print(cov) 
          covr::codecov(coverage = cov, token = Sys.getenv("CODECOV_TOKEN")) # Use token for private repos
        shell: Rscript {0}