name: Test & Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  covr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Check R version
        run: |
          Rscript --version
        shell: bash

      - name: Install system dependencies (including bcftools)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            bcftools
        shell: bash

      - name: Install R package dependencies (including rcmdcheck)
        run: |
          install.packages(c("rcmdcheck", "remotes", "BiocManager"), repos = "https://cloud.r-project.org", Ncpus = 2)
          options(repos = BiocManager::repositories())
          BiocManager::install(ask = FALSE, update = FALSE)
          remotes::install_deps(dependencies = TRUE, Ncpus = 2)
          if (!requireNamespace("rcmdcheck", quietly = TRUE)) {
            stop("rcmdcheck package is required but was not installed.")
          }
        shell: Rscript {0}

      - name: Run tests (devtools::test)
        run: |
          if (!requireNamespace("devtools", quietly = TRUE)) {
            install.packages("devtools", repos = "https://cloud.r-project.org")
          }
          options(crayon.enabled = TRUE)
          devtools::test(stop_on_failure = TRUE, reporter = "summary")
        shell: Rscript {0}

      - name: Calculate and upload coverage (only if check passed)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          if (!requireNamespace("covr", quietly = TRUE)) {
            stop("covr package not found. It should have been installed from Suggests.")
          }
          cov <- covr::package_coverage(type = "tests")
          print(cov)
          covr::codecov(coverage = cov, token = Sys.getenv("CODECOV_TOKEN"))
        shell: Rscript {0}
