name: Test & Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  covr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Check R version
        run: |
          Rscript --version
        shell: bash

      - name: Install system dependencies (including bcftools)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libz-dev libbz2-dev liblzma-dev \
            bcftools
        shell: bash

      - name: Install R package dependencies (including rcmdcheck)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::covr
          needs: |
            check
            coverage

      - name: Check package using rcmdcheck (runs tests)
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"warning"'
          check-dir: '"check"'

      - name: Calculate and upload coverage (only if check passed)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          if (!requireNamespace("covr", quietly = TRUE)) {
            stop("covr package not found. It should have been installed from Suggests.")
          }
          cov <- covr::package_coverage(type = "tests")
          print(cov)
          covr::codecov(coverage = cov, token = Sys.getenv("CODECOV_TOKEN"))
        shell: Rscript {0}
